language: c
script: make
compiler: gcc
before_install:
  - wget http://launchpadlibrarian.net/102057170/g++-4.6-multilib_4.6.3-1ubuntu5_amd64.deb
  - sudo dpkg -i g++-4.6-multilib_4.6.3-1ubuntu5_amd64.deb
  - sudo apt-get clean
  - sudo apt-get update 
  - sudo apt-get install --fix-missing gcc-multilib